'use strict';

const { query } = require('../lib/mariadb');
const dbApi = require('../lib/db');
const shared = require('./serverService.shared');

async function buildNginxUpstreamSnippet() {
  const rows = await query(
    `SELECT id, name, public_ip, private_ip, role, enabled, meta_json, sort_order
     FROM streaming_servers WHERE enabled = 1 AND role IN ('edge','main')
     ORDER BY sort_order ASC, id ASC`
  );
  const lines = [];
  lines.push('# Upstream to stream origins (generated by IPTV Panel)');
  lines.push(
    '# Paste inside http {} on your load balancer, then proxy_pass http://panel_stream_origins;'
  );
  lines.push('upstream panel_stream_origins {');
  lines.push('    least_conn;');
  let any = false;
  for (const row of rows) {
    const meta = shared.parseMeta(row.meta_json);
    const port = parseInt(meta.upstream_port, 10) || 80;
    const backend = String(row.private_ip || row.public_ip || '').trim();
    if (!backend) continue;
    any = true;
    lines.push(`    server ${backend}:${port};  # ${row.name || row.id}`);
  }
  if (!any) {
    lines.push(
      '    # Add public_ip or private_ip on edge/main servers, or set meta_json.upstream_port'
    );
    lines.push('    server 127.0.0.1:80;');
  }
  lines.push('}');
  return lines.join('\n');
}

async function buildFullLbNginxConfig() {
  const upstream = await buildNginxUpstreamSnippet();
  return `${upstream}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    location / {
        proxy_pass http://panel_stream_origins;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    }
}
`;
}

async function selectProxyServer(originServerId) {
  const proxies = await dbApi.getProxyRelationships(originServerId);
  if (!proxies || !proxies.length) return null;

  for (const row of proxies) {
    const health = await shared.getServerHealthStatus(row.server_id);
    if (!health.fresh) continue;
    return {
      serverId: row.server_id,
      server: {
        ...row,
        meta_json: shared.parseMeta(row.meta_json),
        domains: [],
      },
      health,
    };
  }
  return null;
}

async function buildProxyUpstreamConfig(proxyServerId) {
  const origins = await dbApi.getOriginServersForProxy(proxyServerId);
  if (!origins || !origins.length) return '';

  const lines = [
    '# Upstream origins for proxy server (generated by IPTV Panel)',
  ];
  lines.push('upstream panel_proxy_upstreams {');
  for (const origin of origins) {
    const meta = shared.parseMeta(origin.meta_json || {});
    const upstreamPort = parseInt(meta.upstream_port, 10) || 80;
    const ip = String(origin.private_ip || origin.public_ip || '').trim();
    if (!ip) continue;
    lines.push(
      `    server ${ip}:${upstreamPort};  # ${origin.name || origin.server_id}`
    );
  }
  lines.push('}');
  return lines.join('\n');
}

module.exports = {
  buildNginxUpstreamSnippet,
  buildFullLbNginxConfig,
  selectProxyServer,
  buildProxyUpstreamConfig,
};
